[project]
name = "nsm"
version = "0.1.0"
authors = [
    { name = "keejkrej", email = "ctyjackcao@outlook.com" }
]
description = "Visualize NSM HDF5 datasets"
requires-python = ">=3.12,<3.13"
dependencies = [
    "arviz>=0.18",
    "h5py>=3.11",
    "matplotlib>=3.8",
    "numpy>=2",
    "pymc>=5.16",
    "pywavelets>=1.5",
    "scikit-image>=0.24",
    "scikit-learn>=1.5",
    "scipy>=1.13",
]

[project.optional-dependencies]
collaborator = [
    "numba>=0.59",
]

[project.scripts]
nsm-crop = "nsm.crop:main"
nsm-raw = "nsm.plot_raw:main"
nsm-preprocess = "nsm.preprocess:main"
nsm-detect = "nsm.peak_detect:main"
nsm-track = "nsm.track:main"
nsm-diffusion = "nsm.diffusion:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nsm"]
