[project]
name = "nsm"
version = "0.1.0"
authors = [
    { name = "keejkrej", email = "ctyjackcao@outlook.com" }
]
description = "Visualize NSM HDF5 datasets"
requires-python = ">=3.12,<3.13"
dependencies = [
    "h5py>=3.11",
    "imageio>=2.33",
    "imageio-ffmpeg>=0.5",
    "matplotlib>=3.8",
    "numpy>=2",
    "scipy>=1.11",
]

[project.scripts]
nsm-raw = "nsm.viz:main"
nsm-statistics = "nsm.statistics:main"
nsm-preprocess = "nsm.preprocess:main"
nsm-movie-raw = "nsm.movie:main_movie_raw"
nsm-movie-preprocess = "nsm.movie:main_movie_preprocess"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nsm"]
